# Generated by Django 4.1.4 on 2023-01-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alensso', '0004_order_alter_product_pics_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Ordered'), ('C', 'Checked Out'), ('P', 'Pending To Arrive'), ('D', 'Delivered')], default='O', max_length=20, null=True),
        ),
    ]
